### ISSUE TITLE
GUI can not open file vtex_c for Underlords Pc

### ISSUE THREAD

**Issue by cristianireyes** [SteamDatabase/ValveResourceFormat#153]
Hello!

Game: Dota Underlords
Made with the ultimate version of GUI.

When I try to open a file to export to png I get the following error:

**TEXTURE:**
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ValveResourceFormat.ResourceTypes.TextureDecompressors.DecompressBlockDXT5(Int32 x, Int32 y, Int32 width, Byte[] blockStorage, Span`1 pixels, Int32 stride, Boolean yCoCg, Boolean normalize, Boolean invert)
   at ValveResourceFormat.ResourceTypes.TextureDecompressors.UncompressDXT5(SKImageInfo imageInfo, BinaryReader r, Span`1 data, Int32 w, Int32 h, Boolean yCoCg, Boolean normalize, Boolean invert)
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap()
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, Package currentPackage)
```
**"REDI":**
```
ResourceEditInfoBlock_t
{
	Struct m_InputDependencies[0] =
	[
	]
	Struct m_AdditionalInputDependencies[2] =
	[
		ResourceInputDependency_t
		{
			CResourceString m_ContentRelativeFilename = "panorama/images/heroes/spellicons/alchemist_acid_spray.png"
			CResourceString m_ContentSearchPath = "dac"
			uint32 m_nFileCRC = 0xC76A86EB
			uint32 m_nFlags = 0x00000002
		}
		ResourceInputDependency_t
		{
			CResourceString m_ContentRelativeFilename = "panorama/images/heroes/spellicons/alchemist_acid_spray.txt"
			CResourceString m_ContentSearchPath = "dac"
			uint32 m_nFileCRC = 0x00000000
			uint32 m_nFlags = 0x00000001
		}
	]
	Struct m_ArgumentDependencies[8] =
	[
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "___OverrideInputData___"
			CResourceString m_ParameterType = "BinaryBlobArg"
			uint32 m_nFingerprint = 0x78D0E112
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "fast"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "minmipsize"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "maxmipsize"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00100000
			uint32 m_nFingerprintDefault = 0x00100000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "panorama/images/heroes/spellicons/alchemist_acid_spray.png"
			CResourceString m_ParameterType = "ImageArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "panorama/images/heroes/spellicons/alchemist_acid_spray.png"
			CResourceString m_ParameterType = "BinaryBlobArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "etc"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "maxcompiledtextureres"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
	]
	Struct m_SpecialDependencies[3] =
	[
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x0000000B
			uint32 m_nUserData = 0x00000000
		}
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version Image YCoCg Conversion"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x00000001
			uint32 m_nUserData = 0x00000000
		}
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version Mip None"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x00000001
			uint32 m_nUserData = 0x00000000
		}
	]
	Struct m_CustomDependencies[0] =
	[
	]
	Struct m_AdditionalRelatedFiles[0] =
	[
	]
	Struct m_ChildResourceList[0] =
	[
	]
	Struct m_ExtraIntData[1] =
	[
		ResourceEditIntData_t
		{
			CResourceString m_Name = "IsChildResource"
			int32 m_nInt = 1
		}
	]
	Struct m_ExtraFloatData[0] =
	[
	]
	Struct m_ExtraStringData[0] =
	[
	]
}
```
**"DATA":**
```
VTEX Version = 1
Width        = 128
Height       = 128
Depth        = 1
NonPow2W     = 0
NonPow2H     = 0
Reflectivity = ( 0.403815, 0.658277, 0.040104, 0.340243 )
NumMipLevels = 1
Picmip0Res   = 0
Format       = 2 (VTEX_FORMAT_DXT5)
Flags        = 0x0000000F
             | 0x00000001 = VTEX_FLAG_SUGGEST_CLAMPS
             | 0x00000002 = VTEX_FLAG_SUGGEST_CLAMPT
             | 0x00000004 = VTEX_FLAG_SUGGEST_CLAMPU
             | 0x00000008 = VTEX_FLAG_NO_LOD
Extra Data   = 2 entries:
               [ Entry 0: VTEX_EXTRA_DATA_FALLBACK_BITS - 1024 bytes ]
               [ Entry 1: VTEX_EXTRA_DATA_4 - 12 bytes ]
```

**File:** 
[alchemist_acid_spray_png.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/3319725/alchemist_acid_spray_png.zip)

If someone can tell me what's going on I appreciate it.

Regards!

**Comment by xPaw** [comment]
Use up to date VRF.
