### ISSUE TITLE
GUI can not open file VTEX_FORMAT_RGBA8888

### ISSUE THREAD

**Issue by cristianireyes** [SteamDatabase/ValveResourceFormat#157]
Hello!

Game: Dota Underlords
Made with the ultimate version of GUI (22/6/2019).

When I try to open a file to export to png I get the following error:
**TEXTURE**
```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at ValveResourceFormat.ResourceTypes.TextureDecompressors.ReadRGBA8888(BinaryReader r, Int32 w, Int32 h)
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap()
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, Package currentPackage)
```
**REDI**
```
ResourceEditInfoBlock_t
{
	Struct m_InputDependencies[0] =
	[
	]
	Struct m_AdditionalInputDependencies[2] =
	[
		ResourceInputDependency_t
		{
			CResourceString m_ContentRelativeFilename = "panorama/images/synergyicons/undead.txt"
			CResourceString m_ContentSearchPath = "dac"
			uint32 m_nFileCRC = 0x00000000
			uint32 m_nFlags = 0x00000001
		}
		ResourceInputDependency_t
		{
			CResourceString m_ContentRelativeFilename = "panorama/images/synergyicons/undead.psd"
			CResourceString m_ContentSearchPath = "dac"
			uint32 m_nFileCRC = 0xCF428429
			uint32 m_nFlags = 0x00000002
		}
	]
	Struct m_ArgumentDependencies[8] =
	[
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "___OverrideInputData___"
			CResourceString m_ParameterType = "BinaryBlobArg"
			uint32 m_nFingerprint = 0xED7312C1
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "fast"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "minmipsize"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "maxmipsize"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00100000
			uint32 m_nFingerprintDefault = 0x00100000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "panorama/images/synergyicons/undead.psd"
			CResourceString m_ParameterType = "ImageArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "panorama/images/synergyicons/undead.psd"
			CResourceString m_ParameterType = "BinaryBlobArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "etc"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
		ResourceArgumentDependency_t
		{
			CResourceString m_ParameterName = "maxcompiledtextureres"
			CResourceString m_ParameterType = "IntArg"
			uint32 m_nFingerprint = 0x00000000
			uint32 m_nFingerprintDefault = 0x00000000
		}
	]
	Struct m_SpecialDependencies[3] =
	[
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x0000000B
			uint32 m_nUserData = 0x00000000
		}
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version Image Dilate Color"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x00000001
			uint32 m_nUserData = 0x00000000
		}
		ResourceSpecialDependency_t
		{
			CResourceString m_String = "Texture Compiler Version Mip None"
			CResourceString m_CompilerIdentifier = "CompileTexture"
			uint32 m_nFingerprint = 0x00000001
			uint32 m_nUserData = 0x00000000
		}
	]
	Struct m_CustomDependencies[0] =
	[
	]
	Struct m_AdditionalRelatedFiles[0] =
	[
	]
	Struct m_ChildResourceList[0] =
	[
	]
	Struct m_ExtraIntData[1] =
	[
		ResourceEditIntData_t
		{
			CResourceString m_Name = "IsChildResource"
			int32 m_nInt = 1
		}
	]
	Struct m_ExtraFloatData[0] =
	[
	]
	Struct m_ExtraStringData[0] =
	[
	]
}
```
**DATA**
```
VTEX Version = 1
Width        = 128
Height       = 128
Depth        = 1
NonPow2W     = 0
NonPow2H     = 0
Reflectivity = ( 0.209404, 0.209404, 0.209404, 0.311416 )
NumMipLevels = 1
Picmip0Res   = 0
Format       = 4 (VTEX_FORMAT_RGBA8888)
Flags        = 0x0000000F
             | 0x00000001 = VTEX_FLAG_SUGGEST_CLAMPS
             | 0x00000002 = VTEX_FLAG_SUGGEST_CLAMPT
             | 0x00000004 = VTEX_FLAG_SUGGEST_CLAMPU
             | 0x00000008 = VTEX_FLAG_NO_LOD
Extra Data   = 2 entries:
               [ Entry 0: VTEX_EXTRA_DATA_FALLBACK_BITS - 1024 bytes ]
               [ Entry 1: VTEX_EXTRA_DATA_COMPRESSED_MIP_SIZE - 12 bytes ]
                   [ 1 mips, sized: 10106 ]
Mip level 0 - buffer size: 4096
```
File:
undead_psd.vtex_c
[undead_psd.vtex_c.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/3323110/undead_psd.vtex_c.zip)

If someone can tell me what's going on I appreciate it.

Regards!

**Comment by xPaw** [comment]
`CalculateBufferSizeForMipLevel` is still messed up and doesn't work as a generic formula for all texture formats.

I had this crap before but it was just as broken:
https://github.com/SteamDatabase/ValveResourceFormat/blob/f13d54b8fc5041389d1cd5dcabe7ce6401c86df7/ValveResourceFormat/Resource/ResourceTypes/Texture.cs#L350-L362

@Perryvw, have ideas on how to calculate it properly once and for all?
