### ISSUE TITLE
Unsupported "NORMAL" DXGI_FORMAT.R8G8B8A8_UNORM

### ISSUE THREAD

**Issue by legoj15** [SteamDatabase/ValveResourceFormat#159]
When trying to export a DOTA 2 courier model (specifically Amaterasu), VRF GUI throws an exception stating:
```
System.NotImplementedException: Unsupported "NORMAL" DXGI_FORMAT.R8G8B8A8_UNORM
   at ValveResourceFormat.Blocks.VBIB.ReadVertexAttribute(Int32 offset, VertexBuffer vertexBuffer, VertexAttribute attribute) in E:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\Blocks\VBIB.cs:line 184
   at GUI.Types.Renderer.MeshObject.WriteObject(StreamWriter objStream, StreamWriter mtlStream, String mtlFilename, Resource resource) in E:\GitHub\ValveResourceFormat\GUI\Types\Renderer\MeshObject.cs:line 286
   at GUI.MainForm.ExportToolStripMenuItem_Click(Object sender, EventArgs e) in E:\GitHub\ValveResourceFormat\GUI\MainForm.cs:line 1135
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I tried debugging in VS, but something wasn't cooperating and all I got was the dialogue box

Here is the vmesh_c file: [amaterasu.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/3324719/amaterasu.zip)
It can be found in the DOTA 2 pak in ``models/items/couriers/amaterasu``

The program continues to write an obj & mtl file, but both are less than 300 bytes

**Comment by aditya369007** [comment]
I am also facing this issue with other models as well.

**Comment by bentraje** [comment]
Hi. Is there an update on this?
I am experiencing the same problem :(
