### ISSUE TITLE
System.IO.EndOfStreamException

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#169]
I am facing this issue:
`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at ValveResourceFormat.ResourceTypes.TextureDecompressors.ReadRGBA8888(BinaryReader r, Int32 w, Int32 h)
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap()
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, Package currentPackage)`

can you please help me out?

**Comment by xPaw** [comment]
You need to say what file is giving the issue, and where it can be found.
