### ISSUE TITLE
Export Dropdown not functioning

### ISSUE THREAD

**Issue by Grendor** [SteamDatabase/ValveResourceFormat#184]
### Describe the bug
Seems with the current release, the export dropdown has significant errors. Any time I attempt to export a vmesh as OBJ, it throws an error and exports a 1kb empty OBJ. 

### Reference file in a Valve game
Dota: Underlords
"\Underlords\game\dac\pak01_dir.vpk\root\models\underlords\enno\enno_model_7c5be61f.vmesh_c"

### Expected behavior
I expected this to...well...actually export a proper OBJ like it usually would.

### Version info
VRF 0.0.16, on Windows 10.

### Additional context
It seems that this happens for every model from this particular game. Error readout is as follows:

************** Exception Text **************
System.NotImplementedException: Unsupported "NORMAL" DXGI_FORMAT.R8G8B8A8_UNORM
   at ValveResourceFormat.Blocks.VBIB.ReadVertexAttribute(Int32 offset, VertexBuffer vertexBuffer, VertexAttribute attribute)
   at GUI.Types.Renderer.MeshObject.WriteObject(StreamWriter objStream, StreamWriter mtlStream, String mtlFilename, Resource resource)
   at GUI.MainForm.ExportToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by xPaw** [comment]
Can you try latest build from master? There's a link to apoveyor in the readme.
