### ISSUE TITLE
Gman model from HL:A fails to open

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [SteamDatabase/ValveResourceFormat#204]
```
************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'ValveResourceFormat.ResourceTypes.KeyValuesOrNTRO' to type 'ValveResourceFormat.ResourceTypes.BinaryKV3'.
   at ValveResourceFormat.ResourceTypes.AnimationGroup..ctor(ResourceData animationData) in C:\projects\valveresourceformat\ValveResourceFormat\Resource\ResourceTypes\AnimationGroup.cs:line 14
   at ValveResourceFormat.ResourceTypes.Model.GetEmbeddedAnimations() in C:\projects\valveresourceformat\ValveResourceFormat\Resource\ResourceTypes\Model.cs:line 54
   at GUI.Types.Renderer.ModelSceneNode.LoadAnimations() in C:\projects\valveresourceformat\GUI\Types\Renderer\ModelSceneNode.cs:line 199
   at GUI.Types.Renderer.ModelSceneNode..ctor(Scene scene, Model model, String skin, Boolean loadAnimations) in C:\projects\valveresourceformat\GUI\Types\Renderer\ModelSceneNode.cs:line 62
   at GUI.Types.Renderer.GLModelViewer.LoadScene() in C:\projects\valveresourceformat\GUI\Types\Renderer\GLModelViewer.cs:line 51
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in C:\projects\valveresourceformat\GUI\Types\Renderer\GLSceneViewer.cs:line 72
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in C:\projects\valveresourceformat\GUI\Controls\GLViewerControl.cs:line 226
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabPage.set_Visible(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


```
models/characters/gman/gman.vmdl_c

**Comment by CosmicDreamsOfCode** [comment]
Seems any model fails

**Comment by xPaw** [comment]
Get latest unstable build.
