### ISSUE TITLE
VPK case sensitivity on Decompiler

### ISSUE THREAD

**Issue by 09williamsad** [SteamDatabase/ValveResourceFormat#213]
The command line decompiler expects an input vpk directory to have vpk capitalised but the game files have vpk in lower case.

For example
"Decompiler.exe -i pak01_000.VPK" works
"Decompiler.exe -i pak01_000.vpk" has the following error
"System.IO.InvalidDataException: Given file is not a VPK.
   at SteamDatabase.ValvePak.Package.Read(Stream input)
   at SteamDatabase.ValvePak.Package.Read(String filename)
   at Decompiler.Decompiler.ParseVPK(String path) in C:\projects\valveresourceformat\Decompiler\Decompiler.cs:line 483"

This does not prevent usage but is an inconvience and could cause confusion for the unaware.

**Comment by xPaw** [comment]
Give it `_dir` file and then it should work, like `pak01_dir.vpk`. `000` is just content blob.
