### ISSUE TITLE
Error when opening tanaka_eye.vmat_c

### ISSUE THREAD

**Issue by karl-police** [SteamDatabase/ValveResourceFormat#235]
When trying to open ``models/characters/tanaka/materials/tanaka_eye.vmat_c``

I receive an error window with this log:

```
System.Exception: Error linking shaders: 
   at GUI.Types.Renderer.ShaderLoader.LoadPlaneShader(String shaderName, IDictionary`2 arguments)
   at GUI.Types.Renderer.MaterialRenderer..ctor(RenderMaterial renderMaterial, VrfGuiContext vrfGuiContext)
   at GUI.MainForm.<>c__DisplayClass18_2.<ProcessFile>b__2(Object _, EventArgs __)
   at GUI.Types.Renderer.GLMaterialViewer.OnLoad(Object sender, EventArgs e)
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by xPaw** [comment]
Can't repro, provide more info like version, windows version, drivers, gpu, etc.

**Comment by Perryvw** [comment]
Which vpk is this from in the first place? HL:A?
