### ISSUE TITLE
Accessor[2] NORMAL[1621]: Invalid Normal in HL:A dropship.vmdl_c

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#256]
### Reference file in a Valve game

HL:A `models/creatures/combine_dropship/dropship.vmdl_c`

```
[15:06:30.076] System.AggregateException: One or more errors occurred. (Accessor[2] NORMAL[1621]: Invalid Normal)
 ---> SharpGLTF.Validation.DataException: Accessor[2] NORMAL[1621]: Invalid Normal
   at SharpGLTF.IO.ReadContext._ReadFromDictionary(String fileName)
   at SharpGLTF.Schema2.ModelRoot.DeepClone()
   at SharpGLTF.IO.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers)
   at SharpGLTF.IO.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at GUI.Types.Exporter.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\GitHub\ValveResourceFormat\GUI\Types\Exporter\GltfModelExporter.cs:line 98
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass0_0.<Export>b__0(Object _, EventArgs __) in D:\GitHub\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 73
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\GitHub\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

**Comment by xPaw** [comment]
models/creatures/combine_dropship/dropship_cheap.vmdl_c
```
[15:10:10.408] System.AggregateException: One or more errors occurred. (Accessor[12] JOINTS_0[0]: Is out of bounds)
 ---> SharpGLTF.Validation.DataException: Accessor[12] JOINTS_0[0]: Is out of bounds
   at SharpGLTF.IO.ReadContext._ReadFromDictionary(String fileName)
   at SharpGLTF.Schema2.ModelRoot.DeepClone()
   at SharpGLTF.IO.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers)
   at SharpGLTF.IO.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at GUI.Types.Exporter.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\GitHub\ValveResourceFormat\GUI\Types\Exporter\GltfModelExporter.cs:line 98
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass0_0.<Export>b__0(Object _, EventArgs __) in D:\GitHub\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 73
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\GitHub\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```
