### ISSUE TITLE
VTexFormat.DXT5 raising OverflowException

### ISSUE THREAD

**Issue by SinZ163** [SteamDatabase/ValveResourceFormat#26]
VTEX_FORMAT_DXT5 (2) is causing the following error:
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ValveResourceFormat.ThirdParty.DDSImage.DecompressBlockDXT5(Int32 x, Int32 y, Int32 width, Byte[] blockStorage, Bitmap image) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\ThirdParty\DDSImage.cs:line 144
   at ValveResourceFormat.ThirdParty.DDSImage.UncompressDXT5(BinaryReader r, Int32 w, Int32 h) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\ThirdParty\DDSImage.cs:line 131
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap() in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 165
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input) in D:\GitHub\ValveResourceFormat\GUI\MainForm.cs:line 263
```

Test file: `panorama/images/loadingscreens/alliance_abbadon_loadingscreen/loadingscreen_tga.vtex_c`

**Comment by babelshift** [comment]
Pull request: https://github.com/SteamDatabase/ValveResourceFormat/pull/28 should fix this issue.
