### ISSUE TITLE
JOINTS_0[X]: Is out of bounds in glTF export

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#266]
### Describe the bug

Exception: SharpGLTF.Validation.DataException: Accessor[12] JOINTS_0[154]: Is out of bounds

Fixing other skeleton bugs revealed this again.

### Reference file in a Valve game
Dota 2

File: models\items\abaddon\the_sunken_horseman_abaddon_head\the_sunken_horseman_abaddon_head.vmdl_c
File: models\items\bane\heir_of_terror_bane_arms\heir_of_terror_bane_arms.vmdl_c
File: models\items\bounty_hunter\gold_ripperbounty_hunter_back\gold_ripperbounty_hunter_back.vmdl_c
File: models\items\bristleback\wrathrunner_arms\wrathrunner_arms.vmdl_c
File: models\items\chen\desert_wanderer_arms\desert_wanderer_arms.vmdl_c
File: models\items\dark_willow\winter_2018_rose_willow_head\winter_2018_rose_willow_head.vmdl_c
File: models\items\drow\arvalias_legacy_weapon\arvalias_legacy_weapon.vmdl_c
File: models\items\drow\drow_runic_archer_head\drow_runic_archer_head.vmdl_c
File: models\items\drow\frostivus2018_drow_gaze_of_the_zebulon_misc\frostivus2018_drow_gaze_of_the_zebulon_misc.vmdl_c
File: models\items\ember_spirit\magma_spirit_belt\magma_spirit_belt.vmdl_c
File: models\items\huskar\frostivus2018_huskar_ice_age_hunter_head\frostivus2018_huskar_ice_age_hunter_head.vmdl_c

**Comment by faust-hub** [comment]
Now there is a similar problem with exporting a file from Dota 2:
models/items/axe/oni_of_the_red_mist_armor/oni_of_the_red_mist_armor.vmdl_c

Log:
System.AggregateException: One or more errors occurred. (Accessor[32] JOINTS_0[437]: Is out of bounds)
 ---> SharpGLTF.Validation.DataException: Accessor[32] JOINTS_0[437]: Is out of bounds
   at SharpGLTF.Validation.ValidationContext._DataThrow(ValueLocation pname, String msg)
   at SharpGLTF.Validation.ValidationContext.AreJoints(ValueLocation pname, IList`1 joints, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.Accessor._ValidateJoints(ValidationContext validate, String attributeName, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.Accessor.ValidateVertexAttributes(ValidationContext validate, IReadOnlyDictionary`2 attributes, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.MeshPrimitive.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.Mesh.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ModelRoot.OnValidateContent(ValidationContext validate)
   at SharpGLTF.IO.JsonSerializable.ValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.WriteContext._ValidateBeforeWriting(ModelRoot model)
   at SharpGLTF.Schema2.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 456
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 293
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

**Comment by faust-hub** [comment]
Maybe it makes sense in such cases to make an export without a skeleton?

**Comment by xPaw** [comment]
Appears to be fixed.
