### ISSUE TITLE
Unable to load HL:A's distillery map

### ISSUE THREAD

**Issue by SamboyCoding** [SteamDatabase/ValveResourceFormat#305]
### Describe the bug

Upon attempting to load the world for HLA's distillery map (the 'jeff' map) an exception occurs:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at GUI.Types.Renderer.MaterialLoader.GetMaterial(String name) in C:\projects\valveresourceformat\GUI\Types\Renderer\MaterialLoader.cs:line 26
   at GUI.Types.Renderer.RenderableMesh.SetupDrawCalls(Mesh mesh, Dictionary`2 skinMaterials) in C:\projects\valveresourceformat\GUI\Types\Renderer\RenderableMesh.cs:line 102
   at GUI.Types.Renderer.RenderableMesh..ctor(Mesh mesh, VrfGuiContext guiContext, Dictionary`2 skinMaterials) in C:\projects\valveresourceformat\GUI\Types\Renderer\RenderableMesh.cs:line 36
   at GUI.Types.Renderer.ModelSceneNode.LoadMeshes() in C:\projects\valveresourceformat\GUI\Types\Renderer\ModelSceneNode.cs:line 175
   at GUI.Types.Renderer.WorldNodeLoader.Load(Scene scene) in C:\projects\valveresourceformat\GUI\Types\Renderer\WorldNodeLoader.cs:line 23
   at GUI.Types.Renderer.WorldLoader.Load(Scene scene) in C:\projects\valveresourceformat\GUI\Types\Renderer\WorldLoader.cs:line 44
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in C:\projects\valveresourceformat\GUI\Types\Renderer\GLWorldViewer.cs:line 81
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in C:\projects\valveresourceformat\GUI\Types\Renderer\GLSceneViewer.cs:line 87
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in C:\projects\valveresourceformat\GUI\Controls\GLViewerControl.cs:line 248
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
```

### Reference file in a Valve game

Half-Life: Alyx `game/hlvr/maps/a3_distillery.vpk/maps/a3_distillery/world.vwrld_c`

### Expected behavior

The map loads, or at least gives a meaningful error, without throwing an unhandled exception. For example, a3_hotel_lobby_basement works fine.

### Version info

Tried with both unstable build `VRF v0.1.6.1394` and the stable release of 0.1.6 (from 2020-09-16)

### Additional context

I tried manually adding all vpks - including the skybox - to the game content search paths, which didn't help.

**Comment by xPaw** [comment]
From the stacktrace, it looks like it passes a null material here: 

https://github.com/SteamDatabase/ValveResourceFormat/blob/94a4b0a642f4596840a2be7bf8552926b08220e8/GUI/Types/Renderer/RenderableMesh.cs#L102
