### ISSUE TITLE
Arithmetic operation resulted in an overflow on export of model

### ISSUE THREAD

**Issue by CrazyHairGuy** [SteamDatabase/ValveResourceFormat#308]
### Describe the bug
I get "Arithmetic operation resulted in an overflow" error on exporting a model as glTF.

### Reference file in a Valve game
\Half-Life Alyx\game\hlvr\pak01_dir.vpk\models\creatures\zombie_classic\zombie_classic.vmdl_c

### Expected behavior
An exported glTF file

### Version info
VRF v0.1.6.1397, Windows 10 ver. 1909

### Additional context
Here's the console output:

```[16:08:33.287] System.AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint)
   at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint)
   at System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)
   at System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(Double value)
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
   at SharpGLTF.IO._JSonSerializationExtensions.TryWriteValue(Utf8JsonWriter writer, Object value)
   at SharpGLTF.IO.JsonSerializable._SerializeValue(Utf8JsonWriter writer, Object value)
   at SharpGLTF.IO.JsonSerializable.SerializeProperty[T](Utf8JsonWriter writer, String name, IReadOnlyList`1 collection, Nullable`1 minItems)
   at SharpGLTF.Schema2.Accessor.SerializeProperties(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.Serialize(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.SerializeProperty[T](Utf8JsonWriter writer, String name, IReadOnlyList`1 collection, Nullable`1 minItems)
   at SharpGLTF.Schema2.ModelRoot.SerializeProperties(Utf8JsonWriter writer)
   at SharpGLTF.IO.JsonSerializable.Serialize(Utf8JsonWriter writer)
   at SharpGLTF.Schema2.ModelRoot._WriteJSON(Stream sw, Boolean indented)
   at SharpGLTF.IO.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.DeepClone()
   at SharpGLTF.IO.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers)
   at SharpGLTF.IO.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in C:\projects\valveresourceformat\ValveResourceFormat\IO\GltfModelExporter.cs:line 127
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in C:\projects\valveresourceformat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in C:\projects\valveresourceformat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---```

**Comment by xPaw** [comment]
This particular bug was fixed, but there are other issues with the exported model.
