### ISSUE TITLE
Destination array was not long enough during glTF export

### ISSUE THREAD

**Issue by TravisKurt** [SteamDatabase/ValveResourceFormat#346]
### Describe the bug

I have been trying to export a model form SteamVR and I keep getting errors and I have tried to fix them but it still isn't working so I just don't know what to do. 

### What Valve game does this happen in

SteamVR

### Reference file in a Valve game

valvelobby_v2.vmesh_c

### Expected behavior

**Image:** https://imgur.com/a/vRc2xOF

**Code**

```
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.SZArrayHelper.CopyTo[T](T[] array, Int32 index)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SharpGLTF.Schema2._StaticBufferBuilder.Append(Byte[] data)
   at SharpGLTF.Schema2.BufferView._IsolateBufferMemory(_StaticBufferBuilder targetBuffer)
   at SharpGLTF.Schema2.ModelRoot.MergeBuffers()
   at SharpGLTF.Schema2.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers)
   at SharpGLTF.Schema2.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 445
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 293
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[07:57:23.912] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
[08:17:55.801] Export for "valvelobby_v2.vmdl_c" started to "gltf"
[08:21:21.843] System.AggregateException: One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.SZArrayHelper.CopyTo[T](T[] array, Int32 index)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at SharpGLTF.Schema2._StaticBufferBuilder.Append(Byte[] data)
   at SharpGLTF.Schema2.BufferView._IsolateBufferMemory(_StaticBufferBuilder targetBuffer)
   at SharpGLTF.Schema2.ModelRoot.MergeBuffers()
   at SharpGLTF.Schema2.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers)
   at SharpGLTF.Schema2.WriteContext.WriteTextSchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLTF(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 445
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 293
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[08:21:21.852] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues

```

### What version of VRF are you using? On what platform?

VRF v0.1.9.683

**Comment by xPaw** [comment]
Please provide the full file path, and which vpk it is. If this is a workshop item, provide a link to it.

**Comment by TravisKurt** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=928179372

**Comment by xPaw** [comment]
That 130mb mesh was being exported into 2.3gb buffer, which runs past the gltf limitations. I have disabled buffer merging and it exports now.
