### ISSUE TITLE
Failed exporting for unknown reason

### ISSUE THREAD

**Issue by postredaction** [SteamDatabase/ValveResourceFormat#363]
### Describe the bug

Whenever a try to export a headcrab_classic the program always freaks out and fails the export. apperantly this is an issue regarding textures. both supported formats seem to have the issue
Log:
[15:49:03.325] Export for "headcrab_classic.vmdl_c" started to "gltf"
[15:49:04.645] Warning: Unsupported Texture Type g_tMaskParameters
[15:49:07.481] Warning: Unsupported Texture Type g_tDecals
[15:49:10.323] Warning: Unsupported Texture Type g_tNormalBlood
[15:49:12.022] Warning: Unsupported Texture Type g_tIDMask
[15:49:13.204] Warning: Unsupported Texture Type g_tColorBlood
[15:49:14.137] System.AggregateException: One or more errors occurred. (value)
 ---> System.NotFiniteNumberException: value
   at SharpGLTF.Memory.FloatingAccessor.set_Item(Int32 rowIndex, Int32 subIndex, Single value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateRotationChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 415
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 282
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[15:49:14.138] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues

Would like some help on this

### What Valve game does this happen in

Half life:Alyx

### Reference file in a Source 2 game

/pak01_dir/models/creatures/headcrab_classic/headcrab_classic.vmdl_c

### Expected behavior

A clear export with no issues and a working file.

### What version of VRF are you using? On what platform?

0.1.9.731

**Comment by xPaw** [comment]
Use unstable build.
