### ISSUE TITLE
(Index was outside the bounds of the array)  Error when trying to export big HLA maps

### ISSUE THREAD

**Issue by Unitytheproto** [SteamDatabase/ValveResourceFormat#385]
### Describe the bug

every time i try to export the map it will export most of the textures but when it gets to the actual mesh it throws the error (index was outside the bounds of the array)

heres the full error message:
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BPTC.BPTCDecoders.UncompressBC7(BinaryReader r, Int32 w, Int32 h, Boolean hemiOctRB, Boolean invert) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\ThirdParty\BPTCDecoders.cs:line 524
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 389
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material renderMaterial, ModelRoot model, String materialName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 711
   at ValveResourceFormat.IO.GltfModelExporter.CreateGltfMesh(String meshName, Mesh vmesh, ModelRoot model, Boolean includeJoints, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 658
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 376
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 79
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

### What Valve game does this happen in

Half Life: Alyx

### Reference file in a Source 2 game

Half-Life Alyx\game\hlvr\maps\ (i saw it with a2_hideout and a3_c17_processing_plant, there may be more though)

### Expected behavior

i expected it to export the map without throwing errors :p

### What version of VRF are you using? On what platform?

v0.1.10.766

**Comment by lewa-j** [comment]
Fixed by 4ed3c56fef45c901ff91e45ebb9813a848531e94
