### ISSUE TITLE
Unrecognized block type 'LaCo'

### ISSUE THREAD

**Issue by Snoresville** [SteamDatabase/ValveResourceFormat#392]
### Describe the bug

This happens when trying to decompile newer vxml_c files, examples include the ones in Aghanim's Labyrinth 

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

All vxml_c files in game/panorama/layout/custom_game

### Expected behavior

VRF should decompile the XML files, instead we have:

System.ArgumentException: Unrecognized block type 'LaCo'
   at ValveResourceFormat.Resource.ConstructFromType(String input) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 331
   at ValveResourceFormat.Resource.Read(Stream input) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 228
   at ValveResourceFormat.Resource.Read(String filename) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 153
   at GUI.Types.Viewers.Resource.Create(VrfGuiContext vrfGuiContext, Byte[] input) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Resource.cs:line 38
   at GUI.MainForm.ProcessFile(String fileName, Byte[] input, TreeViewPackageTag currentPackage) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 407
   at GUI.MainForm.<>c__DisplayClass20_0.<OpenFile>b__0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 304
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

### What version of VRF are you using? On what platform?

Windows, v0.1.10.766

**Comment by muk-as** [comment]
use new version https://github.com/SteamDatabase/ValveResourceFormat/releases/tag/0.2.0

**Comment by Snoresville** [comment]
Thanks

**Comment by Snoresville** [comment]
Latest version has fixed it.
