### ISSUE TITLE
Unable decompile & export model.

### ISSUE THREAD

**Issue by BobLz108** [SteamDatabase/ValveResourceFormat#402]
### Describe the bug

"An exception occured, view console tab for more information. (One or more errors occurred. (Object reference not set to an instance of an object.)

```
[23:29:36.665] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.GltfModelExporter.GetAllAnimations(Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 883
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 388
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 282
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

pak01_dir.vpk/models/heroes/bounty_hunter/bounty_hunter.vmdl_c

### Expected behavior

decompile & export

### What version of VRF are you using? On what platform?

v0.2.0.864

**Comment by xPaw** [comment]
Provide the full stacktrace from console tab.

**Comment by BobLz108** [comment]
[23:28:33.098] VRF v0.2.0.864
[23:28:38.517] Opening C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk
[23:28:53.276] Export for "bounty_hunter.vmdl_c" started to "gltf"
[23:28:53.491] Warning: Unsupported Texture Type g_tDetail2
[23:28:53.567] Warning: Unsupported Texture Type g_tFresnelWarp
[23:28:53.582] Warning: Unsupported Texture Type g_tMasks1
[23:28:53.634] Warning: Unsupported Texture Type g_tMasks2
[23:28:53.776] Found "" from "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi"
[23:28:53.777] Preloading vpk "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\core\pak01_dir.vpk"
[23:28:53.781] Failed to load "_c". Did you configure VPK paths in settings correctly?
[23:28:53.792] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.GltfModelExporter.GetAllAnimations(Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 883
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 388
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 282
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[23:28:53.793] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
[23:29:36.408] Export for "bounty_hunter.vmdl_c" started to "gltf"
[23:29:36.487] Warning: Unsupported Texture Type g_tDetail2
[23:29:36.491] Warning: Unsupported Texture Type g_tFresnelWarp
[23:29:36.504] Warning: Unsupported Texture Type g_tMasks1
[23:29:36.549] Warning: Unsupported Texture Type g_tMasks2
[23:29:36.663] Failed to load "_c". Did you configure VPK paths in settings correctly?
[23:29:36.665] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.GltfModelExporter.GetAllAnimations(Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 883
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 388
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 282
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
[23:29:36.666] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
[23:30:14.545] Opening bounty_hunter.vmdl_c
[23:30:15.294] OpenGL version: 3.3.0 NVIDIA 511.79
[23:30:15.296] OpenGL vendor: NVIDIA Corporation
[23:30:15.296] OpenGL renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
[23:30:15.297] GLSL version: 3.30 NVIDIA via Cg compiler
[23:30:15.311] Shader 2311134382 (vrf.grid) () compiled and linked succesfully
[23:30:15.368] Shader 2472126206 (hero.vfx) (fulltangent, F_ALPHA_TEST, F_MASKS_1, F_MASKS_2, F_USE_STATUS_EFFECTS_PROXY, F_USE_HERO_EFFECTS_PROXY, F_MORPH_SUPPORTED) compiled and linked succesfully
[23:30:15.379] Failed to load "_c". Did you configure VPK paths in settings correctly?
