### ISSUE TITLE
Cant merge a buffer larger than 2gb

### ISSUE THREAD

**Issue by Unitytheproto** [SteamDatabase/ValveResourceFormat#403]
### Describe the bug

was trying to export the a5_ending as a .GLB from HL:A when after it found all materials it pulled up this error:

[04:52:47.266] System.AggregateException: One or more errors occurred. (Can't merge a buffer larger than 2Gb)
 ---> System.InvalidOperationException: Can't merge a buffer larger than 2Gb
   at SharpGLTF.Schema2.ModelRoot.MergeBuffers()
   at SharpGLTF.Schema2.WriteContext._PreprocessSchema2(ModelRoot model, Boolean imagesAsBufferViews, Boolean mergeBuffers, Int32 buffersMaxSize)
   at SharpGLTF.Schema2.WriteContext.WriteBinarySchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLB(String filePath, WriteSettings settings)
   at SharpGLTF.Schema2.ModelRoot.Save(String filePath, WriteSettings settings)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 451
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 110
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

ive tried exporting it as a gltf but it creates wayyyy to many .bin files which has already been mentioned in another github issue.

### What Valve game does this happen in

Half Life: Alyx

### Reference file in a Source 2 game

A5_ending.vpk/maps/a5_ending/world.vwrld_c

### Expected behavior

I Expected it to export the whole map 

### What version of VRF are you using? On what platform?

v0.1.10.832  Windows 11

**Comment by xPaw** [comment]
#379
