### ISSUE TITLE
error when decompiling vmap_c file

### ISSUE THREAD

**Issue by AestheticallyJanked** [SteamDatabase/ValveResourceFormat#432]
### Describe the bug

```
System.NotImplementedException: WriteText() in ResourceData
   at ValveResourceFormat.Blocks.ResourceData.WriteText(IndentedTextWriter writer) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Blocks\ResourceData.cs:line 20
   at ValveResourceFormat.Block.ToString() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Block.cs:line 35
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 67
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 96
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

### What Valve game does this happen in

All of them

### Reference file in a Source 2 game

it doesn't matter which one

### Expected behavior

i expected to be able to decompile vmap_c files since the option is included within the application

### What version of VRF are you using? On what platform?

latest windows

**Comment by xPaw** [comment]
Open vwrld
