### ISSUE TITLE
"Specified cast is not valid." in ModelAnimation.Frame.SetAttribute

### ISSUE THREAD

**Issue by faust-hub** [SteamDatabase/ValveResourceFormat#441]
### Describe the bug
```
[17:49:29.583] Export for "firemother_firemother_spiderling_ti8_3_styles.vmdl_c" started to "gltf"
[17:49:29.901] Warning: Unsupported Texture Type g_tDetail2
[17:49:29.906] Warning: Unsupported Texture Type g_tFresnelWarp
[17:49:29.933] Warning: Unsupported Texture Type g_tMasks1
[17:49:29.959] Warning: Unsupported Texture Type g_tMasks2
[17:49:30.137] System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Frame.SetAttribute(String bone, String attribute, Object data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Frame.cs:line 25
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 275
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 209
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.FromData(IKeyValueCollection animationData, IKeyValueCollection decodeKey) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 55
[17:49:30.137] System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Frame.SetAttribute(String bone, String attribute, Object data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Frame.cs:line 25
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 275
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 209
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.FromData(IKeyValueCollection animationData, IKeyValueCollection decodeKey) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 55
[17:49:30.138] System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Frame.SetAttribute(String bone, String attribute, Object data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Frame.cs:line 25
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 275
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 209
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.FromData(IKeyValueCollection animationData, IKeyValueCollection decodeKey) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 55
[17:49:30.138] System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Frame.SetAttribute(String bone, String attribute, Object data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Frame.cs:line 25
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 275
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 209
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.FromData(IKeyValueCollection animationData, IKeyValueCollection decodeKey) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 55
[17:49:30.138] System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Frame.SetAttribute(String bone, String attribute, Object data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Frame.cs:line 25
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ReadSegment(Int64 frame, IKeyValueCollection segment, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, Frame& outFrame) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 275
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.ConstructFromDesc(IKeyValueCollection animDesc, IKeyValueCollection decodeKey, AnimDecoderType[] decoderArray, IKeyValueCollection[] segmentArray) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 209
   at ValveResourceFormat.ResourceTypes.ModelAnimation.Animation.FromData(IKeyValueCollection animationData, IKeyValueCollection decodeKey) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ModelAnimation\Animation.cs:line 55
[17:49:30.238] System.NotFiniteNumberException: value
   at SharpGLTF.Memory.FloatingAccessor.set_Item(Int32 rowIndex, Int32 subIndex, Single value)
   at SharpGLTF.Memory.QuaternionArray.set_Item(Int32 index, Quaternion value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateRotationChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 419
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 284
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 82
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[17:49:30.238] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
```
### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

models/items/broodmother/spiderling/firemother_firemother_spiderling_ti8_3_styles/firemother_firemother_spiderling_ti8_3_styles.vmdl_c

models/items/lycan/wolves/_werewolf_samurai_wolves_v1/_werewolf_samurai_wolves_v1.vmdl_c

models/items/furion/treant/supreme_gardener_treants/supreme_gardener_treants.vmdl_c

### Expected behavior

No crashing

### What version of VRF are you using? On what platform?

VRF 0.2.2.1057, Win10 x64

**Comment by xPaw** [comment]
Our animation decoding support is very poor, we need help reverse engineering it correctly.

The relevant code is here: https://github.com/SteamDatabase/ValveResourceFormat/blob/57820d72c533f88d51ffe8475ccd4c63cfb4dfde/ValveResourceFormat/Resource/ResourceTypes/ModelAnimation/Animation.cs#L256-L307

**Comment by faust-hub** [comment]
I would love to take part, but unfortunately I do not understand this. Maybe it makes sense for the decompiler to add the key for decompile without animations? Temporarily

**Comment by faust-hub** [comment]
I also noticed that these models do not have "idle" in the list of available animations. It should be in all animated models. This is clearly Valve's bug. Maybe that's why it crashes...
![image](https://user-images.githubusercontent.com/65903670/188931031-a643d306-b76c-4a07-b885-e339ebafa6a2.png)

**Comment by xPaw** [comment]
> I also noticed that these models do not have "idle" in the list of available animations.

Yes this is a bug with the binary kv3 decoding for ANIM block.
