### ISSUE TITLE
An exception occurred, view console tab for more information. (value)

### ISSUE THREAD

**Issue by NATRON1K** [SteamDatabase/ValveResourceFormat#457]
### Describe the bug

```
[19:47:52.754] Export for "world.vwrld_c" started to "gltf"
[19:47:53.102] Warning: Unsupported Texture Type g_tDetail2
[19:47:53.106] Warning: Unsupported Texture Type g_tFresnelWarp
[19:47:53.110] Warning: Unsupported Texture Type g_tMasks1
[19:47:53.200] Warning: Unsupported Texture Type g_tMasks2
[19:47:53.708] System.NotFiniteNumberException: value
   at SharpGLTF.Memory.QuaternionArray.set_Item(Int32 index, Quaternion value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateRotationChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 419
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 81
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[19:47:53.708] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
[19:56:02.583] Found 0 deleted files totaling 0 B
[19:56:07.749] Export for "world.vwrld_c" started to "gltf"
[19:56:08.113] Warning: Unsupported Texture Type g_tDetail2
[19:56:08.117] Warning: Unsupported Texture Type g_tFresnelWarp
[19:56:08.125] Warning: Unsupported Texture Type g_tMasks1
[19:56:08.216] Warning: Unsupported Texture Type g_tMasks2
[19:56:08.701] System.NotFiniteNumberException: value
   at SharpGLTF.Memory.QuaternionArray.set_Item(Int32 index, Quaternion value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateRotationChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, Model model, String name, Mesh mesh, Skeleton skeleton, String skinMaterialPath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 419
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 81
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_0.<Export>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 88
   at GUI.Forms.GenericProgressForm.<OnShown>b__6_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\GenericProgressForm.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[19:56:08.701] Search existing issues or create a new one here: https://github.com/SteamDatabase/ValveResourceFormat/issues
```

### What Valve game does this happen in

Dota 2

### Reference file in a Source 2 game

D:\SteamLibrary\steamapps\common\dota 2 beta\game\dota\maps\creeptests.vpk\world.vwrld_c

### Expected behavior

Export model

### What version of VRF are you using? On what platform?

W10 X64

**Comment by xPaw** [comment]
I can't reproduce this on latest unstable, it was fixed at some point.
