### ISSUE TITLE
Unable to open some of the vcs files in Aperture Desk Job

### ISSUE THREAD

**Issue by kristiker** [SteamDatabase/ValveResourceFormat#504]
### Describe the bug

Loading either dx11 or vulkan throws an exception with some of the shader files. Shaders that do work use version 65.

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at ValveResourceFormat.CompiledShader.SfConstraintsBlock.ReadIntRange() in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderDataBlocks.cs:line 373
   at ValveResourceFormat.CompiledShader.SfConstraintsBlock..ctor(ShaderDataReader datareader, Int32 blockIndex) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderDataBlocks.cs:line 360
   at ValveResourceFormat.CompiledShader.ShaderFile.ParseFile() in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderFile.cs:line 138
   at GUI.Types.Viewers.CompiledShader.GetShaderCollection(String targetFilename, Package vrfPackage) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\Types\Viewers\CompiledShader.cs:line 85
   at GUI.Types.Viewers.CompiledShader.Create(VrfGuiContext vrfGuiContext, Byte[] input) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\Types\Viewers\CompiledShader.cs:line 47
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in C:\Users\kristi\Documents\GitHub\ValveResourceFormat\GUI\MainForm.cs:line 547
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)```
```

### What Valve game does this happen in

Aperture Desk Job

### Reference file in a Source 2 game

shaders/vfx/vr_complex_vulkan_50_features.vcs
shaders/vfx/vr_depth_only_nonbindless_vulkan_50_features.vcs
shaders/vfx/vr_depth_only_vulkan_50_features.vcs

### Expected behavior

Open and view details

### What version of VRF are you using? On what platform?

0.3.0

**Comment by kristiker** [comment]
On on all three instances of the bug, one of the SfBlocks in vertex shader is 4 bytes larger than expected, that is 156 bytes instead of 152. All 3 instances are with the name `S_FOLIAGE_ANIMATION_ENABLED`.

![image](https://user-images.githubusercontent.com/26466974/210181086-530aedad-f0ce-4da1-b08d-79f4361ae38e.png)
https://github.com/SteamDatabase/ValveResourceFormat/blob/6e561a4a1608506e23c1106d918c7d775b724f58/ValveResourceFormat/CompiledShader/ShaderDataBlocks.cs#L268-L286
