### ISSUE TITLE
Can no longer decompile anything

### ISSUE THREAD

**Issue by hobolyra** [SteamDatabase/ValveResourceFormat#518]
### Describe the bug

I have been unable to extract or even open most file types now with this program. I get RED error, or "ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 1263940355 (0x4B563303)"

`ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 1263940355 (0x4B563303)
   at ValveResourceFormat.ResourceTypes.BinaryKV3.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\BinaryKV3.cs:line 61
   at ValveResourceFormat.Blocks.ResourceEditInfo2.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Blocks\ResourceEditInfo2.cs:line 32
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 192
   at ValveResourceFormat.Resource.Read(String filename) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 182
   at GUI.Types.Viewers.Resource.Create(VrfGuiContext vrfGuiContext, Byte[] input) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Resource.cs:line 40
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 567
   at GUI.MainForm.<>c__DisplayClass22_0.<OpenFile>b__0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 456
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)`

### What Valve game does this happen in

Dota VRF

### Reference file in a Source 2 game

any VRR_C, vsndevts_C, and as of recently most model and texture compiled files.

### Expected behavior

It decompiles or reads the file like it previously was able to.

### What version of VRF are you using? On what platform?

Newest release

**Comment by AHollowedHunter** [comment]
I was about to open a similar issue after trying to read dota2 pak01_dir.vpk/patchnotes/patchnotes.vdpn_c

```
ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 1263940355 (0x4B563303)
   at ValveResourceFormat.ResourceTypes.BinaryKV3.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\BinaryKV3.cs:line 61
   at ValveResourceFormat.Blocks.ResourceEditInfo2.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Blocks\ResourceEditInfo2.cs:line 32
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 192
   at GUI.Types.Viewers.Resource.Create(VrfGuiContext vrfGuiContext, Byte[] input) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Resource.cs:line 36
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 567
   at GUI.MainForm.<>c__DisplayClass22_0.<OpenFile>b__0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 456
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by Marlamin** [comment]
Everything that uses that new version of KV3 will be broken until someone figures out what changed/adds support for it. Give it a bit of time. :)

**Comment by AHollowedHunter** [comment]
```
        public const int MAGIC = 0x03564B56; // VKV3 (3 isn't ascii, its 0x03)
        public const int MAGIC2 = 0x4B563301; // KV3\x01
        public const int MAGIC3 = 0x4B563302; // KV3\x02
        public const int MAGIC4 = 0x4B563303; // KV3\x02

        public KVObject Data { get; private set; }
        public Guid Encoding { get; private set; }
```
```
case MAGIC: ReadVersion1(reader); break;
case MAGIC2: ReadVersion2(reader); break;
case MAGIC3: ReadVersion3(reader); break;
                case MAGIC4: ReadVersion3(reader); break;
                default: throw new UnexpectedMagicException("Invalid KV3 signature", magic, nameof(magic));
```

**Comment by Marlamin** [comment]
Perfectly fine workaround for any files that are otherwise unchanged and don't have whatever they made the new version for. Good sign that not a whole ton changed for _all_ files, at least!

**Comment by xPaw** [comment]
They changed how the flags are stored (resource: soundevent: etc), I haven't found any other changes.

**Comment by MaimedThoughts** [comment]
Hello, I'm new here, and I don't mean to offend anyone, but I came here specifically for this issue, and since I've seen it close, does that mean it's fixed? Shouldn't the fixed version be released if it's been fixed? I really need the most recent decomplier.exe with this issue fixed, and I don't know how to compile it myself.

**Comment by xPaw** [comment]
This is an open source and free project, you needing something doesn't mean anything to us. You can download the latest unstable build which includes this fix.

**Comment by MaimedThoughts** [comment]
@xPaw Sorry if I bothered you, it was not my intention. Could you please tell me where I can find the unstable build? I'm looking through branches, and the master branch appears to be the most recent.

**Comment by Lifeismana** [comment]
https://github.com/SteamDatabase/ValveResourceFormat/actions/runs/4353522640

**Comment by MaimedThoughts** [comment]
@Lifeismana Thank you!
