### ISSUE TITLE
Unexpected header (expected 12) for variable 'HeaderVersion'

### ISSUE THREAD

**Issue by asheroto** [SteamDatabase/ValveResourceFormat#547]
### Describe the bug

I have some old bsp files from 2011 that I'm trying to decompile. I get this error on all of them.

I realize these files are from a long time ago. 😊 I attached them below inside zip files as examples.

### Relevant log output or exception with stacktrace

```shell
[1/1] C:\Users\User\Downloads\Decompiler-windows-x64\achievement_engineer.bsp
File: C:\Users\User\Downloads\Decompiler-windows-x64\achievement_engineer.bsp
ValveResourceFormat.Utils.UnexpectedMagicException: Unexpected header (expected 12) for variable 'HeaderVersion': 20 (0x14)
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 210
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream, String originalPath) in D:\a\ValveResourceFormat\ValveResourceFormat\Decompiler\Decompiler.cs:line 390
        Resource Type: Unknown [Version 0] [Header Version: 20]
        File Size: 1347633750 bytes


--- (No External Resource References Found)


--- (No Deferred Resource References Found)


--- Resource Blocks: Count 0 ---
```

### What game does this happen in

Team Fortress 2

### Reference file in a Source 2 game

[achievement_engineer.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/11310453/achievement_engineer.zip)
[ad_room.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/11310454/ad_room.zip)
[arena_granary.zip](https://github.com/SteamDatabase/ValveResourceFormat/files/11310459/arena_granary.zip)

### Expected behavior

Decompilation

### What version of VRF are you using? On what platform?

0.3.2.1621

**Comment by asheroto** [comment]
Nevermind, thought it decompiled bsps. Closing.
