### ISSUE TITLE
Unknown version for variable 'version': 0 (0x0) for vrman

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#569]
### Describe the bug

In the CS2 game folder, if you open pak01_dir.vpk and try to decompile and export soundevents folder, you get this error. I tried using stable version and the latest unstable build, still same issue. I have CS2 access and I can assure the file is not corrupt.

### Relevant log output or exception with stacktrace

```shell
[06:58:02.495] Extracting soundevents/soundevents_manifest_csgo_imported.vrman_c
[06:58:02.594] System.AggregateException: One or more errors occurred. (Unknown version for variable 'version': 0 (0x0))
 ---> ValveResourceFormat.Utils.UnexpectedMagicException: Unknown version for variable 'version': 0 (0x0)
   at ValveResourceFormat.ResourceTypes.ResourceManifest.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\ResourceManifest.cs:line 39
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 192
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 216
   at GUI.Forms.ExtractProgressForm.<OnShown>b__15_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 111
   --- End of inner exception stack trace ---
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

soundevents/soundevents_manifest_csgo_imported.vrman_c

### Expected behavior

It should decompile and export as every other file.

### What version of VRF are you using? On what platform?

latest unstable build, stable build

**Comment by thouravi** [comment]
Also, getting error to decompile weapons/models/elite/weapon_pist_elite.vmdl_c. Tried on latest unstable build and stable build.

> [07:04:28.207] Extracting weapons/models/elite/weapon_pist_elite.vmdl_c
> [07:04:28.241] System.AggregateException: One or more errors occurred. (value)
>  ---> System.NotFiniteNumberException: value
>    at SharpGLTF.Memory.Vector3Array.set_Item(Int32 index, Vector3 value)
>    at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
>    at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
>    at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
>    at SharpGLTF.Schema2.Animation.CreateScaleChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
>    at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, IDictionary`2 loadedMeshDictionary, String skinName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 542
>    at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 353
>    at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 127
>    at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 222
>    at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 214
>    at GUI.Forms.ExtractProgressForm.<OnShown>b__15_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 101
>    --- End of inner exception stack trace ---
