### ISSUE TITLE
Error System.NotFiniteNumberException: value

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#570]
### Describe the bug

Getting error when trying to decompile and export the weapons/models/elite with the latest unstable build.

### Relevant log output or exception with stacktrace

```shell
[20:48:12.537] Extracting weapons/models/elite/weapon_pist_elite.vmdl_c
[20:48:12.641] System.AggregateException: One or more errors occurred. (value)
 ---> System.NotFiniteNumberException: value
   at SharpGLTF.Memory.FloatingAccessor.set_Item(Int32 rowIndex, Int32 subIndex, Single value)
   at SharpGLTF.Memory.Vector3Array.set_Item(Int32 index, Vector3 value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at SharpGLTF.Schema2.Animation.CreateScaleChannel(Node node, IReadOnlyDictionary`2 keyframes, Boolean linear)
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, IDictionary`2 loadedMeshDictionary, String skinName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 542
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 353
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 127
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 290
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 216
   at GUI.Forms.ExtractProgressForm.<OnShown>b__15_0() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 101
   --- End of inner exception stack trace ---
```

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

weapons/models/elite/weapon_pist_elite.vmdl_c

### Expected behavior

Should be able to decompile and export the files.

### What version of VRF are you using? On what platform?

latest unstable build

**Comment by kristiker** [comment]
Bone scale was infinite this time, animation `firstperson_slideback_both_additive`, frame 1/1, bone 17/17
