### ISSUE TITLE
System.InvalidCastException - Specified cast is not valid

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#578]
### Describe the bug

![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/15676184/8b1d32e9-f5a3-4681-8772-35fd50ee9ea9)

Tried using both the versions (latest and stable), this file was added today in CS2.

particles/blood_impact/blood_impact_friendly.vpcf_c

### Relevant log output or exception with stacktrace

```shell
System.InvalidCastException: Specified cast is not valid.
   at System.Convert.ToDouble(Object value, IFormatProvider provider)
   at ValveResourceFormat.Serialization.IKeyValueCollectionExtensions.GetDoubleProperty(IKeyValueCollection collection, String name) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Serialization\IKeyValueCollection.cs:line 72
   at ValveResourceFormat.Serialization.IKeyValueCollectionExtensions.GetFloatProperty(IKeyValueCollection collection, String name) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Serialization\IKeyValueCollection.cs:line 75
   at GUI.Types.ParticleRenderer.Operators.BasicMovement..ctor(IKeyValueCollection keyValues) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\ParticleRenderer\Operators\BasicMovement.cs:line 22
   at GUI.Types.ParticleRenderer.ParticleControllerFactory.<>c.<.cctor>b__8_18(IKeyValueCollection operatorInfo) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\ParticleRenderer\ParticleControllerFactory.cs:line 48
   at GUI.Types.ParticleRenderer.ParticleControllerFactory.TryCreateOperator(String name, IKeyValueCollection operatorInfo, IParticleOperator& operator) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\ParticleRenderer\ParticleControllerFactory.cs:line 95
   at GUI.Types.ParticleRenderer.ParticleRenderer.SetupOperators(IEnumerable`1 operatorData) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\ParticleRenderer\ParticleRenderer.cs:line 289
   at GUI.Types.ParticleRenderer.ParticleRenderer..ctor(ParticleSystem particleSystem, VrfGuiContext vrfGuiContext, Vector3 pos) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\ParticleRenderer\ParticleRenderer.cs:line 64
   at GUI.Types.Viewers.Resource.<>c__DisplayClass1_1.<Create>b__0(Object _, EventArgs __) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Resource.cs:line 100
   at GUI.Types.Renderer.GLParticleViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLParticleViewer.cs:line 52
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 255
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

particles/blood_impact/blood_impact_friendly.vpcf_c

### Expected behavior

should render fine

### What version of VRF are you using? On what platform?

latest unstable build, stable build

**Comment by UrGenericName** [comment]
Same issue happens when trying to open overpass's vmap_c

**Comment by thouravi** [comment]
> Same issue happens when trying to open overpass's vmap_c

can confirm.

**Comment by thouravi** [comment]
No more error on overpass's vmap_c file with **v4.0.1960**
Still having same issue with particles/blood_impact/blood_impact_friendly.vpcf_c
