### ISSUE TITLE
VRF Crashing during decompile & export (CS2)

### ISSUE THREAD

**Issue by ItsTypho** [SteamDatabase/ValveResourceFormat#579]
### Describe the bug

I am attempting to decompile and export some of the CS2 maps and VRF keeps crashing part way through the process.

I have attempted with the latest stable version v0.4.0.1839 as well as the latest unstable v4.0.1960 (there's a missing 0 on it FYI)
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/31143828/ea4ded54-6427-41a1-8add-a02c56aa8fd8)

Above is a screenshot of Vertigo loaded in the viewer in 0.1960. It begins decompiling and exporting but crashes around the 10% mark on the progress bar. It does export a bunch of the textures, however no actual file for the map as it does not get that far: 
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/31143828/fd97bd1d-2be2-4894-ac20-2af171702391)

Below is a screenshot of my current computer specs running Windows 10:
![image](https://github.com/SteamDatabase/ValveResourceFormat/assets/31143828/ab83f318-9434-4c4a-9dde-c8a6df2e1258)

[VRF_EventViewer_Logs.txt](https://github.com/SteamDatabase/ValveResourceFormat/files/12113915/VRF_EventViewer_Logs.txt)
Windows Event Viewer Logs of the VRF crashes also attached.

### What game does this happen in

Counter-Strike

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_vertigo.vpk

### Expected behavior

I expected the export to finish and the output folder to have all the correct files.

### What version of VRF are you using? On what platform?

v0.4.0.1839 Windows 10

**Comment by pjoe** [comment]
Also crashes for me on 4.0.2078+785e6a97...

Excpetion (decompile and export vertigo as .gltf):
```
[14:31:06.686] System.AggregateException: One or more errors occurred. (Value 0 must be greater than 0. (Parameter 'byteSize'))
 ---> System.ArgumentOutOfRangeException: Value 0 must be greater than 0. (Parameter 'byteSize')
   at SharpGLTF.Guard.MustBeGreaterThan[TValue](TValue value, TValue min, String parameterName)
   at SharpGLTF.Schema2.ModelRoot.CreateBufferView(Int32 byteSize, Int32 byteStride, Nullable`1 target)
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass47_0.<CreateGltfMesh>b__0(OnDiskBufferData vertexBuffer, Int32 vertexBufferIndex) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 767
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at ValveResourceFormat.IO.GltfModelExporter.CreateGltfMesh(String meshName, Mesh vmesh, ModelRoot exportedModel, Boolean includeJoints, String skinMaterialPath, Model model, Int32 meshIndex) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 694
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, String name, Mesh mesh, Node[] joints, IDictionary`2 loadedMeshDictionary, String skinMaterialPath, Model model, Int32 meshIndex) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 610
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, IDictionary`2 loadedMeshDictionary, String skinName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 519
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 177
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 132
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 237
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 86
```

**Comment by xPaw** [comment]
#585
