### ISSUE TITLE
Unknown vertex attribute format R32_UINT

### ISSUE THREAD

**Issue by thouravi** [SteamDatabase/ValveResourceFormat#584]
### Describe the bug

Not able to import the maps/de_ancient.vmap_c file, getting this error.

### Relevant log output or exception with stacktrace

```shell
System.NotImplementedException: Unknown vertex attribute format R32_UINT
   at GUI.Types.Renderer.GPUMeshBufferCache.BindVertexAttrib(RenderInputLayoutField attribute, String attributeName, Int32 attributeLocation, Int32 stride, UInt32 baseVertex) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GPUMeshBufferCache.cs:line 169
   at GUI.Types.Renderer.GPUMeshBufferCache.GetVertexArrayObject(VBIB vbib, Shader shader, RenderMaterial material, UInt32 vtxIndex, UInt32 idxIndex, UInt32 baseVertex) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GPUMeshBufferCache.cs:line 111
   at GUI.Types.Renderer.RenderableMesh.CreateDrawCall(IKeyValueCollection objectDrawCall, IDictionary`2 shaderArguments, RenderMaterial material) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 252
   at GUI.Types.Renderer.RenderableMesh.ConfigureDrawCalls(Dictionary`2 skinMaterials, Boolean firstSetup) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 142
   at GUI.Types.Renderer.RenderableMesh..ctor(Mesh mesh, Int32 meshIndex, Scene scene, Dictionary`2 skinMaterials, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 48
   at GUI.Types.Renderer.ModelSceneNode.LoadMeshes() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 174
   at GUI.Types.Renderer.ModelSceneNode..ctor(Scene scene, Model model, String skin, Boolean loadAnimations) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 61
   at GUI.Types.Renderer.WorldLoader.AddToolModel(Scene scene, Entity entity, String classname, Matrix4x4 transformationMatrix) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 703
   at GUI.Types.Renderer.WorldLoader.LoadEntitiesFromLump(Scene scene, LoadResult result, EntityLump entityLump, String layerName) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 548
   at GUI.Types.Renderer.WorldLoader.Load(Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 71
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLWorldViewer.cs:line 156
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 142
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 316
```

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

maps/de_ancient.vmap_c

### Expected behavior

Open map file

### What version of VRF are you using? On what platform?

VRF v4.0.2073 and VRF v4.0.1941

**Comment by thouravi** [comment]
Same issue while trying to open other map files.
