### ISSUE TITLE
Unknown vertex attribute format R32_FLOAT

### ISSUE THREAD

**Issue by WujekFoliarz** [SteamDatabase/ValveResourceFormat#594]
### Describe the bug

When I try to open gman.vmdl_c in pak01_dir.vpk (half life alyx) I get an error

### Relevant log output or exception with stacktrace

```shell
System.NotImplementedException: Unknown vertex attribute format R32_FLOAT
   at GUI.Types.Renderer.GPUMeshBufferCache.BindVertexAttrib(RenderInputLayoutField attribute, String attributeName, Int32 attributeLocation, Int32 stride, UInt32 baseVertex) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GPUMeshBufferCache.cs:line 172
   at GUI.Types.Renderer.GPUMeshBufferCache.GetVertexArrayObject(VBIB vbib, Shader shader, RenderMaterial material, UInt32 vtxIndex, UInt32 idxIndex, UInt32 baseVertex) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GPUMeshBufferCache.cs:line 110
   at GUI.Types.Renderer.RenderableMesh.CreateDrawCall(IKeyValueCollection objectDrawCall, IDictionary`2 shaderArguments, RenderMaterial material) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 262
   at GUI.Types.Renderer.RenderableMesh.ConfigureDrawCalls(Dictionary`2 skinMaterials, Boolean firstSetup) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 152
   at GUI.Types.Renderer.RenderableMesh..ctor(Mesh mesh, Int32 meshIndex, Scene scene, Dictionary`2 skinMaterials, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 48
   at GUI.Types.Renderer.ModelSceneNode.LoadMeshes() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 174
   at GUI.Types.Renderer.ModelSceneNode..ctor(Scene scene, Model model, String skin, Boolean loadAnimations) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 61
   at GUI.Types.Renderer.GLModelViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLModelViewer.cs:line 111
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 142
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 316
```

### What game does this happen in

Half Life: Alyx

### Reference file in a Source 2 game

Half-Life Alyx\game\hlvr\pak01_000.vpk

### Expected behavior

It should open.
(and decompiling to vmdl (modeldoc) only creates a 1kb file for some reason.)

### What version of VRF are you using? On what platform?

v5.0.2119 Windows 11

**Comment by xPaw** [comment]
Specify the actual path to the model.

**Comment by WujekFoliarz** [comment]
models/characters/gman/gman.vmdl_c
