### ISSUE TITLE
Stream length must be non-negative and less than 2^31 - 1 - origin

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#60]
Seems to be happening on `vanim_c` files.

```
File: models\courier\minipudge\91a45d96\_flying_run.vanim_c
Exception: System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
Parameter name: value
   at System.IO.MemoryStream.set_Position(Int64 value)
   at ValveResourceFormat.StreamHelpers.ReadOffsetString(BinaryReader stream, Encoding encoding) in ValveResourceFormat\Utils\StreamHelpers.cs:line 54
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 221
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 141
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 37
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 157
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 132
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 37
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 157
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 141
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 37
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 157
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 132
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 37
   at ValveResourceFormat.ResourceTypes.NTRO.Read(BinaryReader reader, Resource resource) in ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 23
   at ValveResourceFormat.Resource.Read(Stream input) in ValveResourceFormat\Resource\Resource.cs:line 164
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream) in Decompiler\Program.cs:line 138
```

**Comment by xPaw** [comment]
Reopening because this happens (again?) in Dota 2 on these files:

maps/winter/world_physics.vphys_c
maps/hero_demo_spring/world_physics.vphys_c

```
---------------
Exception: System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'value')
   at System.IO.MemoryStream.set_Position(Int64 value)
   at ValveResourceFormat.StreamHelpers.ReadOffsetString(BinaryReader stream, Encoding encoding) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Utils\StreamHelpers.cs:line 53
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 257
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 153
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 47
   at ValveResourceFormat.ResourceTypes.NTRO.ReadField(Field field, Boolean pointer) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 179
   at ValveResourceFormat.ResourceTypes.NTRO.ReadFieldIntrospection(Field field, NTROStruct& structEntry) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 153
   at ValveResourceFormat.ResourceTypes.NTRO.ReadStructure(ResourceDiskStruct refStruct, Int64 startingOffset) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 47
   at ValveResourceFormat.ResourceTypes.NTRO.Read(BinaryReader reader, Resource resource) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\NTRO.cs:line 33
   at ValveResourceFormat.Resource.Read(Stream input) in D:\GitHub\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 295
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream) in D:\GitHub\ValveResourceFormat\Decompiler\Decompiler.cs:line 299
```
