### ISSUE TITLE
279115896_png.vtex_c export crashes on linux

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveResourceFormat#94]
`panorama/images/econ/autographs/279115896_png.vtex_c` 

`libpng error: invalid after png_start_read_image or png_read_update_info`

```
Unhandled Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.CreateFromHandle(IntPtr handle)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at ValveResourceFormat.ResourceTypes.Texture.ReadPNG() in /home/steamdb/ValveResourceFormat/ValveResourceFormat/Resource/ResourceTypes/Texture.cs:line 202
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap() in /home/steamdb/ValveResourceFormat/ValveResourceFormat/Resource/ResourceTypes/Texture.cs:line 193
   at Decompiler.Decompiler.DumpVPK(Package package, String type, String newType) in /home/steamdb/ValveResourceFormat/Decompiler/Program.cs:line 605
   at Decompiler.Decompiler.ParseVPK(String path) in /home/steamdb/ValveResourceFormat/Decompiler/Program.cs:line 565
   at Decompiler.Decompiler.ProcessFile(String path) in /home/steamdb/ValveResourceFormat/Decompiler/Program.cs:line 151
   at Decompiler.Decompiler.Main(String[] args) in /home/steamdb/ValveResourceFormat/Decompiler/Program.cs:line 87
[1]    12562 abort      dotnet  --input "game/dota/pak01_dir.vpk" --output "game/dota/pak01_dir/"
```

**Comment by xPaw** [comment]
Seems to be related to https://github.com/dotnet/corefx/issues/24354
